name: delivery_app
description: اپلیکیشن مدیریت تحویل بار و فروش
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  mobile_scanner: ^4.0.1
  file_picker: ^6.1.1
  excel: ^2.0.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true